(QUESTION_PRE_BUZZ_EXIT, QUESTION_PRE_BUZZ,
 QUESTION_BUZZ_OPEN, QUESTION_WAIT_ANSWER,
 QUESTION_BUZZ_OPEN_AFTER_WRONG, QUESTION_ANSWERED_RIGHT,
 QUESTION_EVERYBODY_WRONG) = range(7)
END_STATES = (QUESTION_ANSWERED_RIGHT, QUESTION_EVERYBODY_WRONG)

STATES_WITH_BUZZ_OPEN = (
    QUESTION_PRE_BUZZ, QUESTION_BUZZ_OPEN, QUESTION_BUZZ_OPEN_AFTER_WRONG
    )
                         
